In [1]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
print(an_array.shape)


(3,)


In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [4]:
an_array[0] = 888

In [5]:
print(an_array)

[888  33 333]


# rank  2 ndarray


In [6]:
another = np.array([[11,12,14],[21,222,32]])
print(another)
print("the shape is 2 rows,3 col:",another.shape)
print(another[0,0],another[0,1],another[1,0])

[[ 11  12  14]
 [ 21 222  32]]
the shape is 2 rows,3 col: (2, 3)
11 12 21


In [7]:
import numpy as np

ex1 = np.zeros((2,2))
print(ex1)

[[ 0.  0.]
 [ 0.  0.]]


In [8]:
ex3 = np.eye(2,2)
print(ex3)

[[ 1.  0.]
 [ 0.  1.]]


##### ex4 = np.ones((1,2))
print(ex4)

In [12]:
ex1 = np.full((2,2),9)
print(ex1)

[[9 9]
 [9 9]]


In [13]:
ex5 = np.random.random((2,2))
print(ex5)

[[ 0.03098464  0.05913654]
 [ 0.85637292  0.3794851 ]]


# slice indexing

In [14]:
import numpy as np

an_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
a_slice = an_array[:2,1:3]

In [16]:
print(a_slice)

[[12 13]
 [22 23]]


In [17]:
print("before ",an_array)
a_slice[0,0] = 1000
print("after ",an_array)

before  [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
after  [[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


slices are just references,if u changes the slice,array also change

# to create a cpy of array slice

In [19]:
cp_slice = np.array(an_array[:2,1:3])
print(cp_slice)

[[1000   13]
 [  22   23]]


# use both int indexing & slice indexing

In [20]:
row_rank1 = an_array[1,:]
print(row_rank1,row_rank1.shape)

[21 22 23 24] (4,)


In [21]:
print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]

print(col_rank1,col_rank1.shape)
print()
print(col_rank2,col_rank2.shape)


[1000   22   32] (3,)

[[1000]
 [  22]
 [  32]] (3, 1)


In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]


In [23]:
col_indices = np.array([0,1,2,0])
print('\nCol indices picked : ',col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ',row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [24]:
for row,col in zip(row_indices,col_indices):
    print(row,col)

0 0
1 1
2 2
3 0


In [25]:
print(arr[row_indices,col_indices])

[1 5 9 2]


In [26]:
arr[row_indices,col_indices] += 10000
print(arr)

[[10001     2     3]
 [    4 10005     6]
 [    7     8 10009]
 [10002     3     4]]


# boolean indexing

In [ ]:
filter = (arr > 15)
filter

In [28]:
print(arr[filter])

[10001 10005 10009 10002]


In [33]:
arr[(filter) & (arr <10005)]

array([10001, 10002])

# datatypes

In [34]:
ex1 = np.array([11,22])
print(ex1.dtype)

int64


In [35]:
ex2 = np.array([1.1,1.2])
print(ex2.dtype)

float64


In [37]:
ex3 = np.array([11.1,12,13],dtype=np.int64)
print(ex3.dtype)

int64


# ARITHMATIC OPERATION

In [44]:
x = np.array([[11,12],[34,45]],dtype = int)
y = np.array([[11.222,12.2],[3.3,5.4]])
print(x)

[[11 12]
 [34 45]]


In [45]:
print(x+y)

[[ 22.222  24.2  ]
 [ 37.3    50.4  ]]


In [46]:
print(np.add(x,y))

[[ 22.222  24.2  ]
 [ 37.3    50.4  ]]


In [3]:
import numpy as np
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [4]:
np.array([2,2,2,2])

array([2, 2, 2, 2])

In [6]:
arr = np.arange(32).reshape((8,4))

In [7]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [8]:
arr[[1,5,7,2],:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [10]:
arr = np.random.randn(6,3)

In [11]:
arr

array([[ 0.41729991,  0.9948905 , -0.11742733],
       [-0.88847482, -0.4970445 ,  0.39041154],
       [ 1.31786184, -0.93779031,  1.86666942],
       [ 0.74071771, -0.81766821,  0.28204741],
       [ 0.71351312, -2.23795396,  2.60392706],
       [-0.46091802, -0.51197412, -0.13868414]])

In [12]:
np.dot(arr.T,arr)

array([[  3.97049566,  -2.34559155,   4.1949148 ],
       [ -2.34559155,   8.05544772,  -8.04851111],
       [  4.1949148 ,  -8.04851111,  10.52988525]])

In [1]:
import numpy as np
r = np.arange(36).reshape((6,6))

In [2]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [3]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [4]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [5]:
r[:,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [6]:
r[0:6,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [7]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [8]:
r[[2,3],[2,3]]

array([14, 21])

In [9]:
r = np.arange(36).reshape((6,6))

In [10]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [11]:
r[[2,3],[2,3]]

array([14, 21])

In [12]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [1]:
import numpy as np
m = np.random.random((3,4))

In [2]:
%timeit m.sum()

3.28 µs ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [3]:
%timeit np.sum(m)

4.96 µs ± 18.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings